version: '3.9'



services:
  headless-chrome:
    image: browserless/chrome
    container_name: headless-chrome
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.docker
    networks:
      - scraper-network

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper
    restart: always
    volumes:
      - logs:/app/logs/
      - results:/app/results
    networks:
      - scraper-network
    env_file:
      - .env.docker
    depends_on:
      - headless-chrome


volumes:
  logs:
    driver: local
  results:
    driver: local

networks:
  scraper-network:
    driver: bridge