version: '3.9'



services:
  headless-chrome:
    image: browserless/chrome
    container_name: headless-chrome
    restart: always
    ports:
      - 3000:3000
    environment:
      - MAX_CONCURRENT_SESSIONS=5
      - CONNECTION_TIMEOUT=-1
      - ENABLE_DEBUGGER=true
      - ENABLE_CORS=true
      - EXIT_ON_HEALTH_FAILURE=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
    env_file:
      - .env.docker
    networks:
      - scraper-network

  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - http.cors.enabled=true
    env_file:
      - .env.docker
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - scraper-network
  
  kibana:
    image: kibana:8.8.1
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    env_file:
      - .env.docker
    networks:
      - scraper-network
    depends_on:
      - elasticsearch


  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper
    restart: always
    volumes:
      - logs:/app/logs/
      - results:/app/results
    networks:
      - scraper-network
    env_file:
      - .env.docker
    depends_on:
      - headless-chrome


volumes:
  logs:
    driver: local
  results:
    driver: local
  es_data:
    driver: local

networks:
  scraper-network:
    driver: bridge